# Generated by Django 3.2.11 on 2022-01-07 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20220106_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_to_answer',
            field=models.ForeignKey(help_text='Question to answer.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_to_answer', to='questions.question'),
        ),
    ]
