version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: questions_and_answers_server
    container_name: server_django
    depends_on:
      - db
    volumes:
      - ./server:/app
    env_file:
      - ./server/.envs/.postgres
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client/web-app
      dockerfile: ./Dockerfile
    image: questions_and_answers_client
    container_name: client_react
    depends_on:
      - seerver
    volumes:
      - ./client/web-app:/webapp
    ports:
      - "3000:3000"

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./server/.envs/.postgres
    ports:
      - "5431:5432"

volumes:
  db_data: {}